name: Moodle Plugin CI

########################################################################################################################

on: [ push, pull_request ]

########################################################################################################################

jobs:
  call-moodle-ci-workflow:
    uses: Opencast-Moodle/moodle-workflows-opencast/.github/workflows/moodle-ci.yml@main
    with:
      requires-tool-plugin: true
      # Temporarily 500-mod-issue-77 branch is selected to proceed with the tests.
      # This needs to be set back to "main",
      # as soon as https://github.com/Opencast-Moodle/moodle-tool_opencast/pull/103 is merged into "main"
      branch-tool-plugin: 500-mod-issue-77
